export const messsageCategories = [
    {
      id: 1,
      type: "all",
      title: "All Inbox",
      desc: "All messages in your inbox",
      unread: 43,
    },
    {
      id: 2,
      type: "commissions",
      title: "Commissions",
      desc: "Short description for this category of messages",
      unread: 1,
    },
    {
      id: 3,
      type: "sales_training",
      title: "Sales & Training",
      desc: "Short description for this category of messages",
      unread: 6,
    },
    {
      id: 4,
      type: "general",
      title: "General Alerts",
      desc: "Short description for this category of messages",
      unread: 30,
    },
    {
      id: 5,
      type: "documents",
      title: "Documents",
      desc: "Lorem Ipsum",
      unread: 3,
    },
    {
      id: 6,
      type: "service",
      title: "Service & Claims",
      desc: "Lorem Ipsum",
      unread: 1,
    },
    {
      id: 7,
      type: "category",
      title: "Another Category",
      desc: "Lorem Ipsum",
      unread: 2,
    },
  ];
  
  export const messages = [
    {
      id: 1,
      category: 3,
      status: "problem",
      title: "Payment past due",
      policyNumber: "234234523",
      desc: "Your payment is past due on policy #55555555. If full payment is not received by MM/DD/YYYY your policy may lapse. Please make a payment now.",
      subject: 'Payment',
      cta: "Make a Payment",
      ctaUrl: "/payments",
      date: "MM/DD/YYYY",
    },
    {
      id: 2,
      category: 2,
      status: "",
      title: "Claim Received",
      policyNumber: "234234523",
      desc: "We have received your claim. Be sure to read and respond to all claims messages to avoid delay in payout.",
      subject: 'Service & Claim',
      cta: "Track Claim Status",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 3,
      category: 3,
      status: "problem",
      title: "Payment past due",
      policyNumber: "234234523",
      desc: "Your payment is past due on policy #55555555. If full payment is not received by MM/DD/YYYY your policy may lapse. Please make a payment now.",
      cta: "Make a Payment",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 4,
      category: 4,
      status: "",
      title: "Claim Received",
      policyNumber: "234234523",
      desc: "We have received your claim. Be sure to read and respond to all claims messages to avoid delay in payout.",
      cta: "Track Claim Status",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 5,
      category: 5,
      status: "good",
      title: "Payment Made",
      policyNumber: "234234523",
      desc: "We have recieved your payment in full.",
      cta: "View Invoice",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 6,
      category: 5,
      status: "",
      title: "Claim Received",
      policyNumber: "234234523",
      desc: "We have received your claim. Be sure to read and respond to all claims messages to avoid delay in payout.",
      cta: "Track Calim Status",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 7,
      category: 4,
      status: "",
      title: "Claim Received",
      policyNumber: "234234523",
      desc: "We have received your claim. Be sure to read and respond to all claims messages to avoid delay in payout.",
      cta: "Track Calim Status",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 8,
      category: 3,
      status: "",
      title: "Claim Received",
      policyNumber: "234234523",
      desc: "We have received your claim. Be sure to read and respond to all claims messages to avoid delay in payout.",
      cta: "Track Calim Status",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 9,
      category: 2,
      status: "risk",
      title: "Payment past due",
      policyNumber: "234234523",
      desc: "Your payment is past due on policy #55555555. If full payment is not received by MM/DD/YYYY your policy may lapse. Please make a payment now.",
      cta: "Make a payment",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 10,
      category: 3,
      status: "risk",
      title: "Payment past due",
      policyNumber: "234234523",
      desc: "Your payment is past due on policy #55555555. If full payment is not received by MM/DD/YYYY your policy may lapse. Please make a payment now.",
      cta: "Make a Payment",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 11,
      category: 3,
      status: "risk",
      title: "Payment past due",
      policyNumber: "234234523",
      desc: "Your payment is past due on policy #55555555. If full payment is not received by MM/DD/YYYY your policy may lapse. Please make a payment now.",
      cta: "Make a Payment",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 12,
      category: 2,
      status: "risk",
      title: "Payment past due",
      policyNumber: "234234523",
      desc: "Your payment is past due on policy #55555555. If full payment is not received by MM/DD/YYYY your policy may lapse. Please make a payment now.",
      cta: "Make a Payment",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 13,
      category: 4,
      status: "good",
      title: "Payment Made",
      policyNumber: "234234523",
      desc: "Your payment is past due on policy #55555555. If full payment is not received by MM/DD/YYYY your policy may lapse. Please make a payment now.",
      cta: "Make a Payment",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 14,
      category: 4,
      status: "",
      title: "Claim Received",
      policyNumber: "234234523",
      desc: "We have received your claim. Be sure to read and respond to all claims messages to avoid delay in payout.",
      cta: "Track Calim Status",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
    {
      id: 15,
      category: 5,
      status: "",
      title: "Claim Received",
      policyNumber: "234234523",
      desc: "We have received your claim. Be sure to read and respond to all claims messages to avoid delay in payout.",
      cta: "Track Calim Status",
      ctaUrl: "",
      date: "MM/DD/YYYY",
    },
  ];
  